# Estrutura de dados no Pandas

__Series:__

São estruturas de dados em 1D e podem sem criadas a partir de dicionários, arrays, entre outros.
rquiv
Muito proximo de um array em termos de propiedades e métodos

* pd.Series(data, index=index)

__DataFrame:__

São estruturas de dados em 2D e podem ser criadas a partir de dicionários, dados estruturados em 2D, arquivos csv...

Em resumo, Dataframe é uma tabela.

* pd.DataFrame({'key_1:pd.Series(...),'key_n':pd.Deries(...)})

* pd.read_(file)

In [2]:
import pandas as pd
import numpy as np
# Dados
lista_a = [11, 22, 33, 44, 55]
lista_b = ['a', 'b', 'c', 'd', 'e']

Apesar do resutado abaixo ser semelhante a uma tabela, na verdade ela é uma lista indexada com seus indices e valores sendo exibidos de maneira tabular.

In [11]:
serie_1 = pd.Series(lista_a,index=lista_b)
serie_1

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [5]:
serie_1.shape

(5,)

In [6]:
serie_1.ndim

1

In [8]:
serie_1.size

5

In [10]:
serie_1.cumsum()

0     11
1     33
2     66
3    110
4    165
dtype: int64

In [14]:
arr = np.arange(10)**2
arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
serie_3 = pd.Series(arr)
serie_3

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [16]:
dic = {'a': 123, 'b' : 456, 'c': 789}
dic


{'a': 123, 'b': 456, 'c': 789}

In [17]:
serie_4 =pd.Series(dic)
serie_4

a    123
b    456
c    789
dtype: int64

## Criando um DataFrame a partir de um dicionário

No exemplo abaixo temos um data frame composto por um dicionário, que por sua vez, é composto por um atributo chave - valor. O valor é uma serie pandas.

No contexto de um DataFrame as chaves servem como nome das colunas, e as series são os dados de dada coluna.

* pd.DataFrame({'key_1':pd.Series(...), 'key_n':pd.Series(...)})



In [18]:
dic_2 ={'coluna 1': np.arange(10)*5, 'coluna 2': np.arange(10)**2, 'coluna 3' : np.ones (10)}

dic_2

{'coluna 1': array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45]),
 'coluna 2': array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32),
 'coluna 3': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}

In [19]:
dic_2['coluna 1']

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Criando um DataFrame a Partir de uma coluna

In [20]:
df1 = pd.DataFrame(dic_2)
df1

coluna 1  coluna 2  coluna 3
0         0         0       1.0
1         5         1       1.0
2        10         4       1.0
3        15         9       1.0
4        20        16       1.0
5        25        25       1.0
6        30        36       1.0
7        35        49       1.0
8        40        64       1.0
9        45        81       1.0

In [21]:
type(df1)

pandas.core.frame.DataFrame

In [22]:
df1['coluna 1'] # Se usarmos type em df1['coluna 1']  veremos que se trata de uma serie

0     0
1     5
2    10
3    15
4    20
5    25
6    30
7    35
8    40
9    45
Name: coluna 1, dtype: int32

## Criando um DataFrame a partir de um array numpy

In [23]:
arr2 = np.arange(15).reshape(5,3)
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
df2 = pd.DataFrame(arr2)
df2
                   

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [5]:
df3 = pd.read_csv('all_seasons.csv')
df3


Unnamed: 0         player_name team_abbreviation   age  player_height  \
0               0       Dennis Rodman               CHI  36.0         198.12   
1               1   Dwayne Schintzius               LAC  28.0         215.90   
2               2        Earl Cureton               TOR  39.0         205.74   
3               3         Ed O'Bannon               DAL  24.0         203.20   
4               4         Ed Pinckney               MIA  34.0         205.74   
...           ...                 ...               ...   ...            ...   
11140       11140         Maxi Kleber               DAL  28.0         208.28   
11141       11141  Melvin Frazier Jr.               ORL  23.0         195.58   
11142       11142      Meyers Leonard               MIA  28.0         213.36   
11143       11143        Norvel Pelle               PHI  27.0         208.28   
11144       11144         Matt Thomas               TOR  25.0         193.04   

       player_weight                      college  country draft_year  \
0          99.790240  Southeastern Oklahoma State      USA       1986   
1         117.933920                      Florida      USA       1990   
2          95.254320                Detroit Mercy      USA       1979   
3         100.697424                         UCLA      USA       1995   
4         108.862080                    Villanova      USA       1985   
...              ...                          ...      ...        ...   
11140     108.862080                         None  Germany  Undrafted   
11141      97.522280                       Tulane      USA       2018   
11142     117.933920                     Illinois      USA       2012   
11143     104.779752                         None      USA  Undrafted   
11144      86.182480                   Iowa State      USA  Undrafted   

      draft_round  ...  pts   reb  ast  net_rating  oreb_pct  dreb_pct  \
0               2  ...  5.7  16.1  3.1        16.1     0.186     0.323   
1               1  ...  2.3   1.5  0.3        12.3     0.078     0.151   
2               3  ...  0.8   1.0  0.4        -2.1     0.105     0.102   
3               1  ...  3.7   2.3  0.6        -8.7     0.060     0.149   
4               1  ...  2.4   2.4  0.2       -11.2     0.109     0.179   
...           ...  ...  ...   ...  ...         ...       ...       ...   
11140   Undrafted  ...  9.1   5.4  1.1         4.6     0.056     0.140   
11141           2  ...  1.2   0.3  0.1        -2.4     0.018     0.058   
11142           1  ...  6.1   5.1  1.1         5.6     0.029     0.217   
11143   Undrafted  ...  2.1   3.0  0.4       -16.4     0.085     0.237   
11144   Undrafted  ...  4.5   1.4  0.5         1.0     0.017     0.104   

       usg_pct  ts_pct  ast_pct   season  
0        0.100   0.479    0.113  1996-97  
1        0.175   0.430    0.048  1996-97  
2        0.103   0.376    0.148  1996-97  
3        0.167   0.399    0.077  1996-97  
4        0.127   0.611    0.040  1996-97  
...        ...     ...      ...      ...  
11140    0.136   0.605    0.064  2019-20  
11141    0.164   0.480    0.033  2019-20  
11142    0.120   0.640    0.076  2019-20  
11143    0.126   0.521    0.056  2019-20  
11144    0.149   0.663    0.089  2019-20  

[11145 rows x 22 columns]